news_sites:
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_article_links: 'h3.title-container > a'
      article_body: '.epigraph-container'
      article_title: '.title-container'
  elespectador:
    url: https://elespectador.com
    queries:
      homepage_article_links: 'h1,h2 > a'
      article_body: ''
      article_title: ''