news_sites:
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_article_links: '.title-container a'
      article_body: '.contenido'
      article_title: '.titulo'
  elespectador:
    url: https://elespectador.com
    queries:
      homepage_article_links: 'h1 > a , h2 > a'
      article_body: 'p'
      article_title: 'h1'